### ISSUE TITLE
feat: creating base config file

### ISSUE THREAD

**Issue by danielhe4rt** [basementdevs/scyllash#7]
# Feature: Config File

After running/installing the first time, would be good to generate a default config file with all keys used in our project.

Here's a sample: 
```toml
[connection]
hostname = "127.0.0.1"
port = 9142

[cql]
version = "3.3.1"

[prompt]
style = "ScyllaSH> "

[colors]
keyword = "cyan"
string = "green"
number = "yellow"
error = "red"

[metrics]
enabled = true
refresh_interval = 5
```

The most important ATM would be the `connection` section, which can be merged with `clap.rs` if empty. 

## Tasks

- [x] Create a base config file inside the project and append on user `~/.scyllash/config.toml` 
- [x] Configure the same structure for Clap and uses the `config.toml` as fallback in case the user doesn't fill the required fields.
